---
title: "Project description"
---

# Timeline

[Proposal](#project-proposal) due Fri, Oct 21

[Draft report](#draft-report) due Thu, Nov 24

[Peer review](#peer-review) due Mon, Nov 28

[Presentation + slides](#video-presentation--slides) and [final GitHub repo](#reproducibility---organization) due Mon, Dec 5

[Presentation comments](#presentation-comments) due Thu, Dec 8

[Final report](#written-report) due Thu, Dec 8

# Introduction

**TL;DR**: *Ask a question you're curious about and answer it with a dataset of your choice. This is your project in a nutshell.*

**May be too long, but please do read**

The final project for this class will consist of analysis on a dataset of your own choosing.
The dataset may already exist, or you may collect your own data using a survey or by conducting an experiment.
You can choose the data based on your teams' interests or based on work in other courses or research projects.
The goal of this project is for you to demonstrate proficiency in the techniques we have covered in this class (and beyond, if you like) and apply them to a novel dataset in a meaningful way.

The goal is not to do an exhaustive data analysis i.e., do not calculate every statistic and procedure you have learned for every variable, but rather let me know that you are proficient at asking meaningful questions and answering them with results of data analysis, that you are proficient in using R, and that you are proficient at interpreting and presenting the results.
Focus on methods that help you begin to answer your research questions.
You do not have to apply every statistical procedure we learned.
Also, critique your own methods and provide suggestions for improving your analysis.
Issues pertaining to the reliability and validity of your data, andappropriateness of the statistical analysis should be discussed here.

The project is very open ended.
You should create some kind of compelling visualization(s) of this data in R.
There is no limit on what tools or packages you may use but sticking to packages we learned in class is required.
You do not need to visualize all of the data at once.
A single high-qualityvisualization will receive a much higher grade than a large number of poor-quality visualizations.
Also pay attention to your presentation.
Neatness, coherency, and clarity will count.
All analyses must be done in RStudio, using R, and all components of the project **must be reproducible** (with the exception of the presentation).

## Data

The dataset you pick should have at least 50 observations and 10 to 20 variables.
If you set your hearts on a dataset that has fewer observations or variables than what's suggested here, that might still be ok; use these numbers as guidance for a successful proposal, not as minimum requirements.
Picking a dataset that has a variety of numeric and categorical variables can lead to interesting opportunities, and hence is recommended, but is not required.You can find data wherever you like, but here are some recommendations to get you started.
You shouldn't feel constrained to datasets that are already in a tidy format, you can start with data that needs cleaning and tidying, scrape data off the web, or collect your own data.

-   [Awesome public datasets](https://github.com/awesomedata/awesome-public-datasets)
-   [Bikeshare data portal](https://www.bikeshare.com/data/)
-   [Data.gov](https://www.data.gov/)
-   [Data is Plural](https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit#gid=0)
-   [Durham Open Data Portal](https://live-durhamnc.opendata.arcgis.com/)
-   [Edinburgh Open Data](https://edinburghopendata.info/)
-   [CORGIS: The Collection of Really Great, Interesting, Situated Datasets](https://think.cs.vt.edu/corgis/csv/)
-   [Google Dataset Search](https://datasetsearch.research.google.com/)
-   [Harvard Dataverse](https://dataverse.harvard.edu/)
-   [IPUMS survey data from around the world](https://ipums.org/)
-   [Los Angeles Open Data](https://data.lacity.org/browse)
-   [NHS Scotland Open Data](https://www.opendata.nhs.scot/)
-   [NYC OpenData](https://opendata.cityofnewyork.us/)
-   [Open access to Scotland's official statistics](https://statistics.gov.scot/home)
-   [PRISM Data Archive Project](https://www.icpsr.umich.edu/icpsrweb/content/ICPSR/fenway.html)
-   [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/index.php)
-   [UK Government Data](https://data.gov.uk/)
-   [UN data](http://data.un.org/)
-   [US Government Data](https://sctyner.github.io/static/presentations/Misc/GraphicsGroupISU/2018-11-16-us-govt-data.html)
-   [Youth Risk Behavior Surveillance System (YRBSS)](https://chronicdata.cdc.gov/Youth-Risk-Behaviors/DASH-Youth-Risk-Behavior-Surveillance-System-YRBSS/q6p7-56au)

## Deliverables

You have three deliverables for this project: proposal, presentation, and write-up.
Instructions and requirements for each are outlined below.

### Proposal

The `proposal.qmd` file should contain the three following sections.

1.  Introduction: In this part you need to introduce the questions you are interested in answering with the data.
    What observations and variables this question is concerned with?
    If you can state why this question is important, even better.
    You should also address ethical concerns about the data you're using, if any.

2.  Data: Place your data in the data folder and add dimensions and data dictionary to the README in that folder.
    For your data dictionary, follow the structure and the formatting outlined in the README in the template repo.
    Then print out the output of tibble::glimpse() or skimr::skim() of your data frame.

3.  Data analysis plan: Your data analysis plan should clearly state the outcome (Y) and predictor (X) variables you will use to answer your question.
    You should also conduct simple exploratory analysis (including summary statistics and visualizations) to get some preliminary idea about answers to your questions and discuss what the result of this analysis indicates.
    Additionally, you should describe any next steps you have planned for your project.
    Note that your plans do not need to be exhaustive, and you will be free to change them later as you see fit, especially as you learn more about statistical techniques that you can use building on your preliminary exploratory analysis.

### Presentation

You have 5 minutes (maximum) to present your findings.
You can use this time however you like, but you must make sure that each team member says something substantial.

Your presentation should not just be an account of everything you tried ("then we did this, then we did this, etc."), instead it should convey what choices you made, and why, and what you found.

You will prepare slides for your final presentation using the **xaringan** package.
A template is provided in the presentation folder in your template repo, and it's called presentation.Rmd.
If you choose to include any images other than the ones you create with R (e.g., a ggplot) in your presentation, make sure to create a folder called in images in the presentation folder and add these images to this folder.
Before you finalize your presentation, make sure your chunks are turned off with echo = FALSE, except for any code you particularly want to discuss in your presentation, if any.

## Summary

Write a short summary (150--200) words of your project that conveys the main points of your presentation to someone who has not watched your presentation.
This summary can include the questions your project addressed, the specific methods you have used (e.g., exploratory analysis, logistic regression, etc.), your key results, and conclusion.
If necessary, you can include a plot in this section to show an important finding of your project.
This summary should be included in the README.Rmd of your repository.
If you choose to include a plot, then make sure that you have the chunk option set to echo = FALSE so that the R code for the plot can be hidden.
Further details of your results and additional plots should be included in your presentation.

------------------------------------------------------------------------

### Logistics

You will work on the project with your lab teams.

The four primary deliverables for the final project are

-   A written, reproducible executive summary detailing your analysis
-   A GitHub repository corresponding to your report
-   Slides + a presentation
-   Formal peer review on another team's project

------------------------------------------------------------------------

## Topic ideas {#topic-ideas}

Identify 2-3 data sets you're interested in potentially using for the final project.
If you're unsure where to find data, you can use the list of potential data sources in the [Tips + Resources](#tips--resources) section as a starting point.
It may also help to think of topics you're interested in investigating and find data sets on those topics.

The purpose of submitting project ideas is to give you time to find data for the project and to make sure you have a data set that can help you be successful in the project.
**Therefore, you must use one of the data sets submitted as a topic idea, unless otherwise notified by the teaching team.**

The data sets should meet the following criteria:

-   At least 500 observations

-   At least 10 columns

-   At least 6 of the columns must be useful and unique predictor variables.

    -   Identifier variables such as "name", "social security number", etc. are not useful predictor variables.
    -   If you have multiple columns with the same information (e.g. "state abbreviation" and "state name"), then they are not unique predictors.

-   At least one variable that can be identified as a reasonable response variable.

    -   The response variable can be quantitative or categorical.

-   A mix of quantitative and categorical variables that can be used as predictors.

-   Observations should reasonably meet the independence condition.
    Therefore, avoid data with repeated measures, data collected over time, etc.

-   You may not use data that has previously been used in any course materials, or any derivation of data that has been used in course materials.

**Please ask a member of the teaching team if you're unsure whether your data set meets the criteria.**

For each data set, include the following:

#### Introduction and data

-   State the source of the data set.
-   Describe when and how it was originally collected (by the original data curator, not necessarily how you found the data)
-   Describe the observations and the general characteristics being measured in the data

#### Research question

-   Describe a research question you're interested in answering using this data.

#### Glimpse of data

-   Use the `glimpse` function to provide an overview of each data set

Submit the PDF of the topic ideas to Gradescope.
Mark all pages associated with each data set.

## Project proposal {#project-proposal}

The purpose of the project proposal is to help you think about your analysis strategy early.

Include the following in the proposal:

### Section 1 - Introduction

The introduction section includes

-   an introduction to the subject matter you're investigating
-   the motivation for your research question (citing any relevant literature)
-   the general research question you wish to explore
-   your hypotheses regarding the research question of interest.

### Section 2 - Data description

In this section, you will describe the data set you wish to explore.
This includes

-   description of the observations in the data set,
-   description of how the data was originally collected (not how you found the data but how the original curator of the data collected it).

### Section 3 - Analysis approach

In this section, you will provide a brief overview of your analysis approach.
This includes:

-   Description of the response variable.
-   Visualization and summary statistics for the response variable.
-   List of variables that will be considered as predictors
-   Regression model technique (multiple linear regression and logistic regression)

### Data dictionary (aka code book)

Submit a data dictionary for all the variables in your data set in the `README` of your project repo, in the `data` folder.
Link to this file from your proposal writeup.

### Submission

Push all of your final changes to the GitHub repo, and submit the PDF of your proposal to Gradescope.

### Proposal grading

| Total                | 10 pts |
|----------------------|--------|
| **Introduction**     | 3 pts  |
| **Data description** | 2 pts  |
| **Analysis plan**    | 4 pts  |
| **Data dictionary**  | 1 pts  |

Each component will be graded as follows:

-   **Meets expectations (full credit)**: All required elements are completed and are accurate.
    The narrative is written clearly, all tables and visualizations are nicely formatted, and the work would be presentable in a professional setting.

-   **Close to expectations (half credit)**: There are some elements missing and/or inaccurate.
    There are some issues with formatting.

-   **Does not meet expectations (no credit)**: Major elements missing.
    Work is not neatly formatted and would not be presentable in a professional setting.

## Draft report {#draft-report}

The purpose of the draft and peer review is to give you an opportunity to get early feedback on your analysis.
Therefore, the draft and peer review will focus primarily on the exploratory data analysis, modeling, and initial interpretations.

Write the draft in the **written-report.qmd** file in your project repo.
You do not need to submit the draft on Gradescope.

Below is a brief description of the sections to focus on in the draft:

### Introduction and data

This section includes an introduction to the project motivation, data, and research question.
Describe the data and definitions of key variables.
It should also include some exploratory data analysis.
All of the EDA won't fit in the paper, so focus on the EDA for the response variable and a few other interesting variables and relationships.

### Methodology

This section includes a brief description of your modeling process.
Explain the reasoning for the type of model you're fitting, predictor variables considered for the model including any interactions.
Additionally, show how you arrived at the final model by describing the model selection process, any variable transformations (if needed), and any other relevant considerations that were part of the model fitting process.

### Results

In this section, you will output the final model and include a brief discussion of the model assumptions, diagnostics, and any relevant model fit statistics.

This section also includes initial interpretations and conclusions drawn from the model.

## Peer review {#peer-review}

Critically reviewing others' work is a crucial part of the scientific process, and STA 210 is no exception.
Each lab team will be assigned two other teams's projects to review.
Each team should push their draft to their GitHub repo by the due date.
One lab in the following week will be dedicated to the peer review, and all reviews will be due by the end of that lab session.

During the peer review process, you will be provided read-only access to your partner teams' GitHub repos.
Provide your review in the form of GitHub issues to your partner team's GitHub repo using the issue template provided.
The peer review will be graded on the extent to which it comprehensively and constructively addresses the components of the partner team's report: the research context and motivation, exploratory data analysis, modeling, interpretations, and conclusions.

### Pairings

#### Section 1 - M 1:45PM - 3:00PM

| Team being reviewed | Reviewer 1     | Reviewer 2     |
|---------------------|----------------|----------------|
| chaa_chaa_chaa      | yay_stats      | stat_over_flow |
| dekk                | chaa_chaa_chaa | yay_stats      |
| eight               | dekk           | chaa_chaa_chaa |
| housecats           | eight          | dekk           |
| krafthouse          | housecats      | eight          |
| rrawr               | krafthouse     | housecats      |
| stat_over_flow      | rrawr          | krafthouse     |
| yay_stats           | stat_over_flow | rrawr          |

#### Section 2 - M 3:30PM - 4:45PM

| Team being reviewed | Reviewer 1       | Reviewer 2       |
|---------------------|------------------|------------------|
| a_plus_plus_plus    | we_r             | tina             |
| predictors          | a_plus_plus_plus | we_r             |
| sixers              | predictors       | a_plus_plus_plus |
| soy_nuggets         | sixers           | predictors       |
| tina                | soy_nuggets      | sixers           |
| we_r                | tina             | soy_nuggets      |

#### Section 3 - M 5:15PM - 6:30PM

| Team being reviewed              | Reviewer 1                       | Reviewer 2                       |
|----------------------------------|----------------------------------|----------------------------------|
| down_to_earth_goats              | the_three_musketeers             | team_five                        |
| ginger_and_stats                 | down_to_earth_goats              | the_three_musketeers             |
| pineapple_wedge_and_diced_papaya | ginger_and_stats                 | down_to_earth_goats              |
| statchelorettes                  | pineapple_wedge_and_diced_papaya | ginger_and_stats                 |
| statisix                         | statchelorettes                  | pineapple_wedge_and_diced_papaya |
| stats_squad                      | statisix                         | statchelorettes                  |
| team_five                        | stats_squad                      | statisix                         |
| the_three_musketeers             | team_five                        | stats_squad                      |

### Process and questions

Spend \~30 mins to review each team's project.

-   Find your team name on the **Reviewer 1** and **Reviewer 2** columns.
-   For each of the columns, find the name of the team to review in the **Team being reviewed** column. You should already have access to this team's repo.
-   Open the repo of the team you're reviewing, read their project draft, and browser around the rest of their repo.
-   Then, go to the Issues tab in that repo, click on New issue, and click on Get started for the Peer review issue. Fill out this issue, answering the following questions:
    -   Peer review by: \[NAME OF TEAM DOING THE REVIEW\]

    -   Names of team members that participated in this review: \[FULL NAMES OF TEAM MEMBERS DOING THE REVIEW\]

    -   Describe the goal of the project.

    -   Describe the data used or collected, if any.
        If the proposal does not include the use of a specific dataset, comment on whether the project would be strengthened by the inclusion of a dataset.

    -   Describe the approaches, tools, and methods that will be used.

    -   Is there anything that is unclear from the proposal?

    -   Provide constructive feedback on how the team might be able to improve their project.
        Make sure your feedback includes at least one comment on the statistical modeling aspect of the project, but do feel free to comment on aspects beyond the modeling.

    -   What aspect of this project are you most interested in and would like to see highlighted in the presentation.

    -   Provide constructive feedback on any issues with file and/or code organization.

    -   (Optional) Any further comments or feedback?

## Written report {#written-report}

Your written report must be completed in the `written-report.qmd` file and must be reproducible.
All team members should contribute to the GitHub repository, with regular meaningful commits.

Before you finalize your write up, make sure the printing of code chunks is off with the option `echo = FALSE`.

**You will submit the PDF of your final report on Gradescope.**

The PDF you submit must match the files in your GitHub repository *exactly*.
The mandatory components of the report are below.
You are free to add additional sections as necessary.
The report, including visualizations, should be **no more than 10 pages long.** is no minimum page requirement; however, you should comprehensively address all of the analysis and report.

Be selective in what you include in your final write-up.
The goal is to write a cohesive narrative that demonstrates a thorough and comprehensive analysis rather than explain every step of the analysis.

You are welcome to include an appendix with additional work at the end of the written report document; however, grading will largely be based on the content in the main body of the report.
You should assume the reader will not see the material in the appendix unless prompted to view it in the main body of the report.
The appendix should be neatly formatted and easy for the reader to navigate.
It is not included in the 10-page limit.

The written report is worth 40 points, broken down as follows

| Total                         | 40 pts |
|-------------------------------|--------|
| **Introduction/data**         | 6 pts  |
| **Methodology**               | 10 pts |
| **Results**                   | 14 pts |
| **Discussion + conclusion**   | 6 pts  |
| **Organization + formatting** | 4 pts  |

[Click here](/documents/project-report-rubric.pdf "Project rubric") for a PDF of the written report rubric.

### Introduction and data

This section includes an introduction to the project motivation, data, and research question.
Describe the data and definitions of key variables.
It should also include some exploratory data analysis.
All of the EDA won't fit in the paper, so focus on the EDA for the response variable and a few other interesting variables and relationships.

#### Grading criteria

The research question and motivation are clearly stated in the introduction, including citations for the data source and any external research.
The data are clearly described, including a description about how the data were originally collected and a concise definition of the variables relevant to understanding the report.
The data cleaning process is clearly described, including any decisions made in the process (e.g., creating new variables, removing observations, etc.) The explanatory data analysis helps the reader better understand the observations in the data along with interesting and relevant relationships between the variables.
It incorporates appropriate visualizations and summary statistics.

### Methodology

This section includes a brief description of your modeling process.
Explain the reasoning for the type of model you're fitting, predictor variables considered for the model including any interactions.
Additionally, show how you arrived at the final model by describing the model selection process, interactions considered, variable transformations (if needed), assessment of conditions and diagnostics, and any other relevant considerations that were part of the model fitting process.

#### Grading criteria

The analysis steps are appropriate for the data and research question.
The group used a thorough and careful approach to select the final model; the approach is clearly described in the report.
The model selection process took into account potential interaction effects and addressed any violations in model conditions.
The model conditions and diagnostics are thoroughly and accurately assessed for their model.
If violations of model conditions are still present, there was a reasonable attempt to address the violations based on the course content.

### Results

This is where you will output the final model with any relevant model fit statistics.

Describe the key results from the model.
The goal is not to interpret every single variable in the model but rather to show that you are proficient in using the model output to address the research questions, using the interpretations to support your conclusions.
Focus on the variables that help you answer the research question and that provide relevant context for the reader.

#### Grading criteria

The model fit is clearly assessed, and interesting findings from the model are clearly described.
Interpretations of model coefficients are used to support the key findings and conclusions, rather than merely listing the interpretation of every model coefficient.
If the primary modeling objective is prediction, the model's predictive power is thoroughly assessed.

### Discussion + Conclusion

In this section you'll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions.
In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved.
Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here.
Lastly, this section will include ideas for future work.

#### Grading criteria

Overall conclusions from analysis are clearly described, and the model results are put into the larger context of the subject matter and original research question.
There is thoughtful consideration of potential limitations of the data and/or analysis, and ideas for future work are clearly described.

### Organization + formatting

This is an assessment of the overall presentation and formatting of the written report.

#### Grading criteria

The report neatly written and organized with clear section headers and appropriately sized figures with informative labels.
Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted.
All citations and links are properly formatted.
If there is an appendix, it is reasonably organized and easy for the reader to find relevant information.
All code, warnings, and messages are suppressed.
The main body of the written report (not including the appendix) is no longer than 10 pages.

## Presentation + slides

### Slides

In addition to the written report, your team will also create presentation slides and record a video presentation that summarize and showcase your project.
Introduce your research question and data set, showcase visualizations, and discuss the primary conclusions.
These slides should serve as a brief visual addition to your written report and will be graded for content and quality.

**For submission, convert these slides to a .pdf document, and submit the PDF of the slides on Gradescope.**

The slide deck should have no more than 6 content slides + 1 title slide.
Here is a *suggested* outline as you think through the slides; you [**do not**]{.underline} have to use this exact format for the 6 slides.

-   Title Slide
-   Slide 1: Introduce the topic and motivation
-   Slide 2: Introduce the data
-   Slide 3: Highlights from EDA
-   Slide 4: Final model
-   Slide 5: Interesting findings from the model
-   Slide 6: Conclusions + future work

### Video presentation

For the video presentation, you can speak over your slide deck, similar to the lecture content videos.
**The video presentation must be no longer than 8 minutes.** It is fine if the video is shorter than 8 minutes, but it cannot exceed 8 minutes.
You may use can use any platform that works best for your group to record your presentation.
Below are a few resources on recording videos:

-   [Recording presentations in Zoom](https://kb.siue.edu/61721)
-   [Apple Quicktime for screen recording](https://support.apple.com/en-gb/guide/quicktime-player/qtp97b08e666/mac)
-   [Windows 10 built-in screen recording functionality](https://www.youtube.com/watch?v=OfPbr1mRDuo)
-   [Kap for screen recording](https://getkap.co/)

Once your video is ready, upload the video to Warpwire, then embed the video in an new discussion post on Conversations.

#### To upload your video to Warpwire:

-   Click the Warpwire tab in the course Sakai site.
-   Click the "+" and select "Upload files".
-   Locate the video on your computer and click to upload.
-   Once you've uploaded the video to Warpwire, click to share the video and copy the video's URL. You will need this when you post the video in the discussion forum.

#### To post the video to the discussion forum

-   Click the Presentations tab in the course Sakai site.
-   Click the Presentations topic.
-   Click "Start a new conversation".
-   Make the title "Your Team Name: Project Title". For example, "Teaching Team: Our Awesome Presentation".
-   Click the Warpwire icon (between the table and shopping cart icons).
-   Select your video, then click "Insert 1 item." This will embed your video in the conversation.
-   Under the video, paste the URL to your video.
-   You're done!

## Presentation comments {#presentation-comments}

Each student will be assigned 2 presentations to watch.
Your viewing assignments will be posted later in the semester.

Watch the group's video, then click "Reply" to post a question for the group.
You may not post a question that's already been asked on the discussion thread.
Additionally, the question should be (i) substantive (i.e. it shouldn't be "Why did you use a bar plot instead of a pie chart"?), (ii) demonstrate your understanding of the content from the course, and (iii) relevant to that group's specific presentation, i.e demonstrating that you've watched the presentation.

*This portion of the project will be assessed individually.*

### Pairings

Find your team name in the first column, watch videos from teams in the second column and leave comments.

| Reviewer                         | First video to review            | Second video to review           |
|:---------------------------------|:---------------------------------|:---------------------------------|
| Ginger and Stats                 | Eight                            | We R                             |
| Krafthouse                       | Ginger and Stats                 | Eight                            |
| Soy Nuggets                      | Krafthouse                       | Ginger and Stats                 |
| Down To Earth Goats              | Soy Nuggets                      | Krafthouse                       |
| A+++                             | Down To Earth Goats              | Soy Nuggets                      |
| Team Five                        | A+++                             | Down To Earth Goats              |
| Rrawr                            | Team Five                        | A+++                             |
| Housecats                        | Rrawr                            | Team Five                        |
| Dekk                             | Housecats                        | Rrawr                            |
| Stat OverFlow                    | Dekk                             | Housecats                        |
| The Three Musketeers             | Stat OverFlow                    | Dekk                             |
| Predictors                       | The Three Musketeers             | Stat OverFlow                    |
| Stats Squad                      | Predictors                       | The Three Musketeers             |
| Statisix                         | Stats Squad                      | Predictors                       |
| Sixers                           | Statisix                         | Stats Squad                      |
| Yay Stats                        | Sixers                           | Statisix                         |
| TINA                             | Yay Stats                        | Sixers                           |
| Statchelorettes                  | TINA                             | Yay Stats                        |
| Pineapple Wedge and Diced Papaya | Statchelorettes                  | TINA                             |
| Chaa Chaa Chaa                   | Pineapple Wedge and Diced Papaya | Statchelorettes                  |
| We R                             | Chaa Chaa Chaa                   | Pineapple Wedge and Diced Papaya |
| Eight                            | We R                             | Chaa Chaa Chaa                   |

## Reproducibility + organization

All written work (with exception of presentation slides) should be reproducible, and the GitHub repo should be neatly organized.

The GitHub repo should have the following structure:

-   `README`: Short project description and data dictionary

-   `written-report.qmd` & `written-report.pdf`: Final written report

-   `/data`: Folder that contains the data set for the final project.

-   `/previous-work`: Folder that contains the `topic-ideas` and `project-proposal` files.

-   `/presentation`: Folder with the presentation slides.

    -   If your presentation slides are online, you can put a link to the slides in a `README.md` file in the `presentation` folder.

Points for reproducibility + organization will be based on the reproducibility of the written report and the organization of the project GitHub repo.
The repo should be neatly organized as described above, there should be no extraneous files, all text in the README should be easily readable.

## Peer teamwork evaluation

You will be asked to fill out a survey where you rate the contribution and teamwork of each team member by assigning a contribution percentage for each team member.
Filling out the survey is a prerequisite for getting credit on the team member evaluation.
If you are suggesting that an individual did less than half the expected contribution given your team size (e.g., for a team of four students, if a student contributed less than 12.5% of the total effort), please provide some explanation.
If any individual gets an average peer score indicating that this was the case, their grade will be assessed accordingly.

If you have concerns with the teamwork and/or contribution from any team members, please email me by the project video deadline.
**You only need to email me if you have concerns**.
Otherwise, I will assume everyone on the team equally contributed and will receive full credit for the teamwork portion of the grade.

## Overall grading

The grade breakdown is as follows:

| Total                              | 100 pts |
|------------------------------------|---------|
| **Topic ideas**                    | 5 pts   |
| **Project proposal**               | 10 pts  |
| **Peer review**                    | 10 pts  |
| **Written report**                 | 40 pts  |
| **Slides + video presentation**    | 20 pts  |
| **Reproducibility + organization** | 5 pts   |
| **Video comments**                 | 5 pts   |
| **Peer teamwork evaluation**       | 5 pts   |

*Note: No late project reports or videos are accepted.*

### Grading summary

Grading of the project will take into account the following:

-   Content - What is the quality of research and/or policy question and relevancy of data to those questions?
-   Correctness - Are statistical procedures carried out and explained correctly?
-   Writing and Presentation - What is the quality of the statistical presentation, writing, and explanations?
-   Creativity and Critical Thought - Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

A general breakdown of scoring is as follows:

-   *90%-100%*: Outstanding effort. Student understands how to apply all statistical concepts, can put the results into a cogent argument, can identify weaknesses in the argument, and can clearly communicate the results to others.
-   *80%-89%*: Good effort. Student understands most of the concepts, puts together an adequate argument, identifies some weaknesses of their argument, and communicates most results clearly to others.
-   *70%-79%*: Passing effort. Student has misunderstanding of concepts in several areas, has some trouble putting results together in a cogent argument, and communication of results is sometimes unclear.
-   *60%-69%*: Struggling effort. Student is making some effort, but has misunderstanding of many concepts and is unable to put together a cogent argument. Communication of results is unclear.
-   *Below 60%*: Student is not making a sufficient effort.

### Late work policy

**There is no late work accepted on this project.** Be sure to turn in your work early to avoid any technological mishaps.
