---
title: "Data import"
subtitle: "Lecture 9"
date: "September 27, 2022"
format: revealjs
---

# Warm up

```{r}
#| echo: false

library(countdown)
```

## While you wait for class to begin...

::: callout-important
Come up with at least one question you'd like to see answered in the Exam 1 review on Thursday.

Go to [slido.com](https://www.slido.com/) and submit your question with the code **#sta199exam1**.

You can also upvote others' questions.
:::

## Announcements {.smaller}

-   Lab 3 due Friday night (11:59 pm) -- but I strongly recommend you finish and submit it before the exam begins!

-   Exam 1 is released on Thursday at noon and is due at 2pm on Monday.

    -   No TA OH during the exam.

    -   I will have OH 4-5pm on Friday (on Zoom).

    -   Any clarification questions must be **emailed to me** only.

    -   No Slack use during the exam, even about non-exam related questions.

## Exam study tips

-   Take notes that you can reference
-   Review feedback given to you on graded work
-   Revisit AEs
-   Review suggested solutions
-   Ask questions

## New resources

On the course website:

-   More links to package documentation on the useful links page: <https://sta199-f22-1.github.io/course-links.html>
-   New page with links to cheatsheets: <https://sta199-f22-1.github.io/computing-cheatsheets.html>

# From last time

## Continue from last time: `ae-06`

::: appex
-   Go to your container and open your `ae-06` project.
-   Render, commit, and push.

::: callout-important
You will see an error.
Read it and do as it says!
:::

- Pull.

- Once again, render, commit, and push.
:::

## Recap of AE {.smaller}

-   A vector can only have one type of elements in it. Placing elements with different types into a vector cases type coercion.
-   Factor is a class that R uses for categorical data and factors allow us to customize order and behaviour of levels.

# Reading data into R

## Reading rectangular data

-   Using [**readr**](https://readr.tidyverse.org/):
    -   Most commonly: `read_csv()`
    -   Maybe also: `read_tsv()`, `read_delim()`, etc.
-   Using [**readxl**](https://readxl.tidyverse.org/): `read_excel()`
-   Using [**googlesheets4**](https://googlesheets4.tidyverse.org/): `read_sheet()` -- We haven't covered this in the videos, but might be useful for your projects

# Application exercise

## `ae-07`

::: appex
-   Go to the course [GitHub org](https://github.com/sta199-f22-1) and find your `ae-07` (repo name will be suffixed with your GitHub name).
-   Clone the repo in your container, open the Quarto document in the repo, and follow along and complete the exercises.
-   Render, commit, and push your edits by the AE deadline -- 3 days from today.
:::
