---
title: "HW 6 - Statistics experience"
categories: "Homework"
editor: visual
---

::: callout-important
This homework is due Friday, Dec 9 at 11:59pm ET.

Homework assignments are individual, not team based.

There is no GitHub repo for this assignment, see below for slide format.
:::

The world of statistics and data science is vast and continually growing!
The goal of the statistics experience assignments is to help you engage with the statistics and data science communities outside of the classroom.

You may submit the statistics experience assignment anytime between now and the deadline.

Each experience has two parts:

1️⃣ Have a statistics experience

2️⃣ Make a slide summarizing on your experience

**You must complete both parts to receive credit.**

## Part 1: Experience statistics outside of the classroom

Complete an activity in one of the categories below.
Under each category are suggested activities.
You do not have to do one these suggested activities.
You are welcome to find other activities as long as they are related to statistics/data science and they fit in one of the six categories.
If there is an activity you'd like to do but you're not sure if it qualifies for the statistics experience, just ask!

### Category 1: Attend a talk or conference

Attend an talk, panel, or conference related to statistics or data science.
If you are attending a single talk or panel, it must be *at least 30 minutes* to count towards the statistics experience.
The event can be in-person or online.

### Category 2: Talk with a statistician/ data scientist

Talk with someone who uses statistics in their daily work.
This could include a professor, professional in industry, graduate student, etc.

### Category 3: Listen to a podcast / watch video

Listen to a podcast or watch a video about statistics and data science.
The podcast or video must be *at least 30 minutes* to count towards the statistics experience.
A few suggestions are below:

-   [rstudio::conf 2022 talks](https://www.youtube.com/watch?v=u1Gzxg8Pd08&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH)
-   [rstudio::global 2021 talks](https://www.rstudio.com/resources/rstudioglobal-2021/)
-   [rstudio::conf 2020 talks](https://www.rstudio.com/resources/rstudioconf-2020/)
-   [Stats + Stories Podcast](https://statsandstories.net/)
-   [Causal Inference Podcast](https://casualinfer.libsyn.com/)
-   [FiveThirtyEight Model Talk](https://fivethirtyeight.com/tag/model-talk/)

This list is not exhaustive.
You may listen to other podcasts or watch other statistics/data science videos not included on this list.
Ask your professor if you are unsure whether a particular podcast or video will count towards the statistics experience.

### Category 4: Participate in a data science competition or challenge

Participate in a statistics or data science competition.
You can participate individually or with a team.

### Category 5: Read a book on statistics/data science

There are *a lot* of books about statistics, data science, and related topics.
A few suggestions are below.
If you decide to read a book that isn't on this list, ask your professor to make sure it counts toward the experience.
Many of these books are available through Duke library.

-   *Weapons of Math Destruction* by Cathy O'Neil
-   *How Charts Lie: Getting Smarter about Visual Information* by Alberto Cairo
-   *The Theory that Would Not Die* by Sharon Bertsch McGrayne
-   *The Art of Statistics: How to learn from data* by David Spiegelhalter
-   *The Signal and the Noise: Why so many predictions fail - but some don't* by Nate Silver
-   *How Charts Lie* by Alberto Cairo
-   [List of books about data science ethics](https://teachdatascience.com/bookclub/)

### Category 6: TidyTuesday

You may also participate in a TidyTuesday challenge.
New data sets are announced on Monday afternoons.You can find more information about TidyTuesday and see the data in the [TidyTuesday GitHub repo](https://github.com/rfordatascience/tidytuesday).

A few guidelines:

✅ Create a GitHub repo for your TidyTuesday submission.
Your repo should include

-   The R Markdown file with all the code needed to reproduce your visualization.
-   A README that includes an image of your final visualization and a short summary (\~ 1 paragraph) about your visualization.

✅ The visualization should include features or customization that are beyond what we've done in class .

✅ Include the link to your GitHub repo in the slide summarizing your experience.

### Category 7: Coding out loud

Watch an episode of [Coding out loud](https://dukecct.github.io/coding-out-loud/) (either live or pre-recorded) and work through the project.

A few guidelines:

✅ Create a GitHub repo for your Coding out loud submission.
Your repo should include

-   The Quarto file with all the code needed to reproduce your visualization.
-   A README that includes an image of your final visualization and a short summary (\~ 1 paragraph) about your visualization.

✅ The final product (visualization, table, etc.) should include features or customization that are beyond what was achieved in the Coding out loud episode.

✅ Include the link to your GitHub repo in the slide summarizing your experience.

## Part 2: Summarize your experience

Make one slide summarizing your experience.
Submit the slide as a PDF on Gradescope.

Include the following on your slide:

-   Name and brief description of the event/podcast/competition/etc.
-   Something you found new, interesting, or unexpected
-   How the event/podcast/competition/etc. connects to something we've done in class.
-   Citation or link to web page for event/competition/etc.

[Click here](https://docs.google.com/presentation/d/1Ua7rmAQn8FaRLxJpxaRvOZfBLIlEjYVxugEaaTcIjMQ/edit?usp=sharing) to see a template to help you get started on your slide.
Your slide does not have to follow this exact format; it just needs to include the information mentioned above and be easily readable (i.e. use a reasonable font size!).
Creativity is encouraged!

# Wrap up

## Submission

-   Go to <http://www.gradescope.com> and click Log in in the top right corner.
-   Click School Credentials Duke Net ID and log in using your Net ID credentials.
-   Click on your STA 199 course.
-   Click on the assignment, and you'll be prompted to submit it.
-   Mark all the pages associated with exercise. All the pages of your homework should be associated with at least one question (i.e., should be "checked"). If you do not do this, you will be subject to lose points on the assignment.
-   Select the first page of your PDF submission to be associated with the "Workflow & formatting" question.

## Grading

This assignment will be graded out of 50 points, based on the quality and depth of your writing.
