{
  "hash": "501a231aa5bf3022d7d61c23f508ee7b",
  "result": {
    "markdown": "---\ntitle: \"Inference overview\"\ncategories: \n  - Application exercise\n  - Answers\neditor: visual\neditor_options: \n  chunk_output_type: console\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrc <- read_csv(\"data/roller_coasters.csv\")\n```\n:::\n\n\nIn this application exercise, we will be looking at a roller coaster and amusement park database by Duane Marden.[^1]\nThis database records multiple features of roller coasters.\nFor the purpose of this activity, we will work with a random sample of 157 roller coasters.\n\n[^1]: [Roller Coaster DataBase](https://rcdb.com/), [UltimateRollerCoaster.com](https://www.ultimaterollercoaster.com/), [ESTEEM: Enhancing Statistics Teachers Education with E-Modules](https://www.fi.ncsu.edu/teams/hirise/).\n\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| **Variable**        | **Description**                                                                                                                                                                                             |\n+:====================+:============================================================================================================================================================================================================+\n| `age_group`         | 1: Older (Built between 1900-1979)                                                                                                                                                                          |\n|                     |                                                                                                                                                                                                             |\n|                     | 2: Recent (1980-1999)                                                                                                                                                                                       |\n|                     |                                                                                                                                                                                                             |\n|                     | 3: Newest (2000-current)                                                                                                                                                                                    |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `coaster`           | Name of the roller coaster                                                                                                                                                                                  |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `park`              | Name of the park where the roller coaster is located                                                                                                                                                        |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `city`              | City where the roller coaster is located                                                                                                                                                                    |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `state`             | State where the roller coaster is located                                                                                                                                                                   |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `type`              | Material of track (Steel or Wooden)                                                                                                                                                                         |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `design`            | How a passenger is positioned in the roller coaster:                                                                                                                                                        |\n|                     |                                                                                                                                                                                                             |\n|                     | Flying: a roller coaster ridden while parallel with the track.                                                                                                                                              |\n|                     |                                                                                                                                                                                                             |\n|                     | Inverted: a roller coaster which uses trains traveling beneath, rather than on top of, the track. Unlike a suspended roller coaster, an inverted roller coaster's trains are rigidly attached to the track. |\n|                     |                                                                                                                                                                                                             |\n|                     | Sit Down: a traditional roller coaster ridden while sitting down.                                                                                                                                           |\n|                     |                                                                                                                                                                                                             |\n|                     | Suspended: a roller coaster using trains which travel beneath the track and pivot on a swinging arm from side to side, exaggerating the track's banks and turns.                                            |\n|                     |                                                                                                                                                                                                             |\n|                     | Stand Up: a coaster ridden while standing up instead of sitting down.                                                                                                                                       |\n|                     |                                                                                                                                                                                                             |\n|                     | Pipeline: a coaster where riders are positioned between the rails instead of above or below.                                                                                                                |\n|                     |                                                                                                                                                                                                             |\n|                     | Wing: a coaster where pairs of riders sit on either side of a roller coaster track in which nothing is above or below the riders.                                                                           |\n|                     |                                                                                                                                                                                                             |\n|                     | 4th Dimension: a coaster where the cars have the ability to rotate on an axis perpendicular to that of the track.                                                                                           |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `year_opened`       | Year when roller coaster opened                                                                                                                                                                             |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `top_speed`         | Maximum speed of roller coaster (mph)                                                                                                                                                                       |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `max_height`        | Highest point of roller coaster (ft)                                                                                                                                                                        |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `drop`              | Length of largest gap between high and low points of roller coaster (ft)                                                                                                                                    |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `length`            | Length of roller coaster track (ft)                                                                                                                                                                         |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `duration`          | Time length of roller coaster ride (sec)                                                                                                                                                                    |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `inversions`        | Whether or not roller coaster flips passengers at any point (Yes or No)                                                                                                                                     |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n| `num_of_inversions` | Number of times roller coaster flips passengers                                                                                                                                                             |\n+---------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+\n\n# Research question 1\n\n> **Is the true proportion of steel roller coasters opened before 1970 different than those opened after 1970?**\n\n-   **Demo:** Create a new variable called `opened_recently` that has a response of `yes` if the roller coaster was opened after 1970, and `no` if the roller coaster was opened during or before 1970. Save this new factor variable in the `rc` data set. Additionally, make `type` a factor variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrc <- rc |>\n  mutate(\n    opened_recently = if_else(year_opened > 1970, \"yes\" , \"no\"), \n    opened_recently = as.factor(opened_recently),\n    type = as.factor(type)\n  ) \n```\n:::\n\n\n-   **Your turn:** Based on the research question, which of the following is the appropriate null hypothesis?\n    a.  $H_0$: $\\mu = 0.5$\n\n    b.  $H_0$: $p > 0.5$\n\n    c.  $H_0$: $\\mu_1 - \\mu_2 = 0$\n\n    d.  $H_0$: $p_1 - p_2 = 0$\n\nThe answer is (d).\n\n-   **Demo:** Write out the appropriate alternative hypothesis in both words and notation.\n\n$H_A$: $p_1 - p_2 \\ne 0$\n\n-   **Demo:** Calculate the observed statistic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npoint_estimate <- rc |>\n  specify(type ~ opened_recently, success = \"Steel\") |>\n  calculate(stat = \"diff in props\", order = c(\"yes\", \"no\"))\n```\n:::\n\n\n-   **Demo:** How do we create a null distribution for this hypothesis test?\n    Write out the steps below.\n\n    1.  Shuffle responses into one pile.\n    2.  Redistribute data into two new piles of size n1 and n2.\n    3.  Calculate new difference in proportions.\n    4.  Repeat steps 1-3 many times to create the null distribution.\n\n-   **Demo:** Create the null distribution with 1,000 repeated samples.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(101821)\n\nnull_dist <- rc %>%\n  specify(type ~ opened_recently, success = \"Steel\") %>%\n  hypothesize(null = \"independence\") %>%\n  generate(1000, type = \"permute\") %>%\n  calculate(stat = \"diff in props\", order = c(\"yes\", \"no\"))\n```\n:::\n\n\n-   **Demo:** Visualize the null distribution and shade in the area used to calculate the p-value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisualize(null_dist) +\n shade_p_value(obs_stat = point_estimate, direction = \"two sided\")\n```\n\n::: {.cell-output-display}\n![](ae-19-inference-overview-A_files/figure-html/null-dist-visualize-1.png){width=672}\n:::\n:::\n\n\n-   **Your turn:** Calculate p-value. Then use the p-value to make your conclusion using a significance level of 0.1 and write out an appropriate conclusion below. Recall that the conclusion has 3 components.\n    -   How the p-value compares to the significance level.\n    -   The decision you make with respect to the hypotheses (reject $H_0$ /fail to reject $H_0$)\n    -   The conclusion in the context of the **alternative hypothesis**.\n\nSince the p-value is smaller than 10%, we reject the null hypothesis in favor of the alternative hypothesis.\nThe data provide convincing evidence that the proportion of steel roller coasters opened before 1970 is different than those opened after 1970.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist |>\n  get_p_value(obs_stat = point_estimate, direction = \"two sided\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Please be cautious in reporting a p-value of 0. This result is an\napproximation based on the number of `reps` chosen in the `generate()` step. See\n`?get_p_value()` for more information.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1       0\n```\n:::\n:::\n\n\n# Research question 2\n\n> **We want to investigate the relationship between how fast a roller coaster goes, and how long a roller coaster lasts. Specifically, we are interested in how well the duration of a roller coaster explains or predicts how fast it is.**\n\n-   **Question:** Based on this research question, which two variables should we use from our data set? Which is our response?\n\n`top_speed` and `duration`.\n\n-   **Demo:** Fit a model predicting `top_speed` from `duration` and display the tidy summary output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspeed_fit <- linear_reg() |>\n  fit(top_speed ~ duration, data = rc) \n\ntidy(speed_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  52.0       4.08       12.8  3.99e-24\n2 duration      0.0560    0.0305      1.83 6.92e- 2\n```\n:::\n:::\n\n\n-   **Your turn:** Use your model to estimate the top speed of a roller coaster if their duration is 155 minutes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduration_155 <- tibble(duration = 155)\n\npredict(speed_fit, new_data = duration_155)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1  60.7\n```\n:::\n:::\n\n\n-   **Demo:** Write out the estimated model in proper notation and interpret the slope coefficient\n\n$\\widehat{top~speed} = 52 + 0.056 \\times duration$\n\nFor each additional second the ride is longer, the predicted top speed of the roller coaster is higher by 0.057 miles per hour, on average.\n\n-   **Question:** The slope you calculated and interpeted above is a sample statistic (an estimate).\n    It is possible (and quite likely) that the true slope of the relationship between durations and top speeds of all roller coasters is not exactly equal to this value.\n    How can we quantify the uncertainty around this estimate?\n\nUse a confidence interval.\n\n-   **Your turn:** Describe how we can construct a bootstrap distribution for the slope of the model predicting `top_speed` from `duration`.\n    1.  Take a bootstrap sample of pairs of `top_speed` and `duration`.\n    2.  Fit a model predicting `top_speed` from `duration` using the bootstrap sample and record the value of the slope.\n    3.  Repeat steps 1 and 2 many times.\n-   **Demo:** Now, construct this bootstrap distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345)\n\nboot_df_slope <- rc |>\n  specify(top_speed ~ duration) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"slope\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 34 rows containing missing values.\n```\n:::\n:::\n\n\n-   **Demo:** Create a 90% confidence interval by filling in the code below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboot_df_slope |>\n  summarize(\n    lower = quantile(stat, 0.05),\n    upper = quantile(stat, 0.95)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n    lower upper\n    <dbl> <dbl>\n1 -0.0195 0.132\n```\n:::\n:::\n\n\n-   **Demo:** Interpret the confidence interval in the context of the problem.\n\nWe are 90% confident that, for each additional second the ride is longer, the predicted top speed of the roller coaster is lower by -0.0195 to higher by 0.132 miles per hour, on average.\n\n-   **Demo:** Now fit a model predicting log of `top_speed` from `duration`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrc <- rc |>\n  mutate(top_speed_log = log(top_speed))\n\nspeed_log_fit <- linear_reg() |>\n  fit(top_speed_log ~ duration, data = rc) \n\ntidy(speed_log_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  3.92     0.0686       57.1  2.15e-89\n2 duration     0.00104  0.000514      2.03 4.48e- 2\n```\n:::\n:::\n\n\n-   **Demo:** Write the estimated model and interpret the slope.\n\n$\\widehat{log(top~speed)} = 3.92 + 0.00104 \\times duration$\n\nRecall that to interpret the slope value we need to exponentiate it!\n\nWhy?\n\n$$\n\\begin{aligned}\nlog(y~for~x + 1) - log(y~for~x) &= \\beta_1 \\\\\nlog\\Big(\\frac{y~for~x + 1}{y~for~x}\\Big) &= \\beta_1 \\\\\ne^{log\\Big(\\frac{y~for~x + 1}{y~for~x}\\Big)} &= e^\\beta_1 \\\\\n\\frac{y~for~x + 1}{y~for~x} &= e^\\beta_1\n\\end{aligned}\n$$\n\nThis implies that our explanatory variable has a multiplicative relationship with our response variable.\n\nFor each additional second the ride is longer, the predicted top speed of the roller coaster is higher by a factor of $e^0.00104 = 1.001$, on average.\n\n# Research question 3\n\n> **We are also interested in investigating if roller coasters opened after 1970 are faster than those opened before. For this question, we want to estimate the difference.**\n\n-   **Question:** How is this different from question one? Should we make a confidence interval or conduct a hypothesis test?\n\nWe are interested in estimating the difference.\nThis suggests we should make a confidence interval.\n\n-   **Demo:** Now, use bootstrapping to estimate the difference between the true speeds of roller coasters before and after 1970.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345)\n\nboot_df <- rc |>\n  specify(top_speed ~ opened_recently) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"diff in means\", order = c(\"yes\", \"no\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 11 rows containing missing values.\n```\n:::\n:::\n\n\n-   **Your turn:** Create a 99% confidence interval and interpret it in the context of the data and the research question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboot_df |>\n  summarize(\n    lower = quantile(stat, 0.005),\n    upper = quantile(stat, 0.995)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  lower upper\n  <dbl> <dbl>\n1  8.88  23.3\n```\n:::\n:::\n\n\nWe are 99% confident that the true mean speed between roller coasters after 1970 are 8.88 to 23.3 mph higher than the true mean speed for roller coasters before 1970.\n\n# Discussion\n\n-   Brainstorm the differences between generating new samples via bootstrapping and permuting. Write down the key differences below. *Hint:* Think back to the different sampling techniques between research question 1 and research questions 2 and 3.\n",
    "supporting": [
      "ae-19-inference-overview-A_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}